modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="simply_wool_to_sting"
version="1.0.0"
displayName="Simply Wool To Sting"
credits="Azureddraig"
displayURL="https://discord.gg/GTgx6tYjg2"
authors="Azureddraig"
description="Turn any wool into string!"

[[dependencies.simply_wool_to_sting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




